services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "fast_api_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
